# Generated by Django 4.2.19 on 2025-04-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Null for unauthenticated uploads', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, help_text='Structured skills/experience extracted from the resume', null=True),
        ),
    ]
