# Generated by Django 4.2.19 on 2025-04-17 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0002_alter_resume_candidate_alter_resume_parsed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='candidate',
            field=models.ForeignKey(blank=True, help_text='Null for unauthenticated sessions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
